Just make it work (I give up)
For some reason, setting cabal to the alias `cabal --project-file=cabal-902.project` in shell-902.nix and then running `cabal build lib:dump-decls` inside this shell fails in CI with the following error and I can't figure out why. This commit does it the old way which means it doesn't work in a local shell (because it doesn't specify --project-file).

```
Run nix-shell shell-902.nix --run 'type cabal; cabal -v build lib:dump-decls'
  nix-shell shell-902.nix --run 'type cabal; cabal -v build lib:dump-decls'
  shell: /usr/bin/bash -e {0}
  env:
    TMPDIR: /home/runner/work/_temp
    NIX_BUILD_SHELL: /nix/store/rhvbjmcfnkg8i2dxpzr114cp1ws7f667-bash-5.2-p15/bin/bash
cabal is aliased to `cabal --project-file=cabal-902.project'
this build was affected by the following (project) config files:
- /home/runner/work/dump-decls/dump-decls/cabal.project
Compiler settings changed, reconfiguring...
CallStack (from HasCallStack):
  withMetadata, called at src/Distribution/Simple/Utils.hs:368:14 in Cabal-3.10.2.1-ACr4SVyJCRPB6t49xa4Way:Distribution.Simple.Utils
Error: cabal: Cannot find the program 'ghc'. User-specified path 'ghc-9.6.2'
does not refer to an executable and the program is not on the system path.
```